### ISSUE TITLE
Create a Dashboard

### ISSUE THREAD

**Issue by princekumarg** [princekumarg/Full-statck-devlopment#3]

**Comment by Amitsingh0808** [comment]
pls assing me this issue

**Comment by pulkitxm** [comment]
Can I get assigned? let me know how to start.

**Comment by princekumarg** [comment]
make a attendence manangment dashboard using html,css,js

**Comment by pulkitxm** [comment]
Explain in brief What is needed

**Comment by princekumarg** [comment]
get the idea from youtube.

**Comment by princekumarg** [comment]
use  html,css,js make a webpage.

**Comment by pulkitxm** [comment]
Describe what type of dashboard , what all things needed ?
